version: 0.2

phases:
  build:
    commands:
      - mkdir -p ./python
      - pip install psycopg2 --target ./python
      - pip freeze > requirements.txt
artifacts:
  discard-paths: no
  files:
    - '**/*'
  type: zip