name: "build"

on:
  workflow_dispatch:

jobs:
  api:
    defaults:
      run:
        shell: "bash"
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      TF_LOG: "info"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "hashicorp/setup-terraform@v1"
      - run: "terraform init -input=false -reconfigure -no-color -upgrade"
      - run: "terraform apply -auto-approve -input=false -no-color"
